import Foundation

/// A prioritized, human-readable judgment about usage behavior.
/// Generated by `InsightEngine` from snapshot history and live quota data.
public struct UsageInsight: Sendable, Identifiable, Equatable {
    /// Stable identifier for dedup (e.g., "depletion-claude")
    public let id: String
    public let category: Category
    public let priority: Priority
    /// One-line headline (e.g., "Session depletes in ~2h")
    public let title: String
    /// 1-2 line explanation or advice
    public let detail: String
    /// Provider this insight applies to; nil for cross-provider
    public let providerId: String?
    /// SF Symbol name
    public let symbolName: String
    /// Visual severity for coloring
    public let severity: Severity

    public init(
        id: String,
        category: Category,
        priority: Priority,
        title: String,
        detail: String,
        providerId: String? = nil,
        symbolName: String,
        severity: Severity
    ) {
        self.id = id
        self.category = category
        self.priority = priority
        self.title = title
        self.detail = detail
        self.providerId = providerId
        self.symbolName = symbolName
        self.severity = severity
    }

    // MARK: - Category

    public enum Category: Sendable, Equatable {
        case depletion
        case pace
        case trend
        case pattern
        case utilization
    }

    // MARK: - Priority

    public enum Priority: Int, Sendable, Comparable, Equatable {
        case critical = 0
        case high = 1
        case medium = 2
        case low = 3

        public static func < (lhs: Self, rhs: Self) -> Bool {
            lhs.rawValue < rhs.rawValue
        }
    }

    // MARK: - Severity

    public enum Severity: Sendable, Equatable {
        case positive   // green — good news
        case neutral    // gray — informational
        case caution    // orange — worth noting
        case urgent     // red — needs attention
    }
}
